words:
  - agarrharr
  - ajeetdsouza
  - anuraghazra
  - ardaku
  - aristocratos
  - babalae
  - biber
  - borai
  - csapp
  - dasel
  - dsnet
  - dtolnay
  - dylanaraps
  - emirpasic
  - feiyue
  - fffaraz
  - flos
  - gokcehan
  - gomod
  - gosimple
  - gping
  - hansimov
  - ibraheemdev
  - ibus
  - indicatif
  - isti
  - jguer
  - jlfwong
  - jorgebucaran
  - junegunn
  - karan
  - kazhnuz
  - kovidgoyal
  - lartians
  - liblaf
  - lkmpg
  - lmintlcx
  - mackwic
  - mholt
  - micheleg
  - mikaelmello
  - mikedh
  - mkdocs
  - mvdan
  - mwaskom
  - nextra
  - notofonts
  - nuitka
  - nukesor
  - nvitop
  - otiai
  - paperwm
  - pappasam
  - patarimi
  - phira
  - pterm
  - pueue
  - pydantic
  - pyinstaller
  - pypa
  - pyvista
  - rclone
  - rekcarc
  - rizsotto
  - sharkdp
  - shimohq
  - shuding
  - sindresorhus
  - svenstaro
  - tiangolo
  - tiktoken
  - tldr
  - tmbo
  - tokei
  - trinkle
  - ttroy
  - twpayne
  - typer
  - typst
  - uanonym
  - vclab
  - vinta
  - vuejs
  - vuepress
  - xampp
  - xinychen
  - xuehai
  - yerong
  - zhiburt
  - zotero
  - zoxide
ignorePaths:
  - "*-lock.*"
  - "*.lock"
  - cspell.config.yaml
dictionaries:
  - bash
  - cpp
  - cpp-legacy
  - cpp-refined
  - dotnet
  - en-gb
  - makefile
  - npm
  - python
  - rust
allowCompoundWords: true
