site_name: Awesome

site_url: https://awesome.liblaf.me

repo_url: https://github.com/liblaf/awesome

edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: dark mode
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch # sponsors only
    - navigation.instant.progress
    - navigation.path # sponsors only
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - styles/index.css

watch:
  - includes

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - tables

plugins:
  - git-authors
  - git-committers:
      branch: main
      repository: liblaf/awesome
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  # - optimize # sponsors only
  - search
