site_name: awesome

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Light Mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    # - search.share
    - content.action.edit
    - content.action.view

plugins:
  - search
  - git-revision-date-localized:
      # enabled: true
      # type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      # enabled: true
      repository: liblaf/awesome
      branch: main
  - git-authors
  # - optimize:
  #   enabled: true
  #   concurrency: 16
  #   optimize_png: true
  #   optimize_png_speed: 4
  #   optimize_png_strip: true
  #   optimize_jpg: true
  #   optimize_jpg_quality: 60
  #   optimize_jpg_progressive: true
  #   cache: true
  #   cache_dir: .cache/plugins/optimize

repo_url: https://github.com/liblaf/awesome

edit_uri: edit/main/docs/
