site_name: Awesome

site_url: https://awesome.liblaf.me

repo_url: https://github.com/liblaf/awesome

edit_uri: edit/main/docs/

extra_css:
  - styles/index.css

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips # sponsors only
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path # sponsors only
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: system preference
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: light mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: dark mode

plugins:
  # built-in
  - meta # sponsors only
  - optimize # sponsors only
  - privacy
  - search:
      lang:
        - en
        - zh
  - social
  - tags
  - typeset # sponsors only
  # external
  - gen-files:
      scripts: []
  - git-authors
  - git-committers:
      repository: liblaf/awesome
      branch: main
  # external-community
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true

markdown_extensions:
  # external > markdown
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      anchorlink: true
  # external > pymdownx
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

watch:
  - includes
