Awesome:
  - agarrharr/awesome-cli-apps
  - avelino/awesome-go
  - awesome-selfhosted/awesome-selfhosted
  - bestofjs/javascript-risingstars
  - fffaraz/awesome-cpp
  - ibraheemdev/modern-unix
  - Kazhnuz/awesome-gnome
  - public-apis/public-apis
  - rust-unofficial/awesome-rust
  - sindresorhus/awesome
  - sindresorhus/awesome-nodejs
  - trackawesomelist/trackawesomelist
  - vinta/awesome-python

Browser:
  - darkreader/darkreader
  - Get-Tech-Stack/TechStack

CLI:
  - ajeetdsouza/zoxide
  - bitwarden/clients
  - charmbracelet/gum
  - charmbracelet/vhs
  - cli/cli
  - commitizen/cz-cli
  - direnv/direnv
  - dylanaraps/neofetch
  - ImageMagick/ImageMagick
  - jgm/pandoc
  - Jguer/yay
  - jlfwong/speedscope
  - junegunn/fzf
  - Nukesor/pueue
  - PaddiM8/kalker
  - pre-commit/pre-commit
  - prettier/prettier
  - rclone/rclone
  - starship/starship
  - svenstaro/miniserve
  - tamasfe/taplo
  - tj/git-extras
  - tldr-pages/tldr
  - tmux/tmux
  - twpayne/chezmoi
  - WayneD/rsync
  - XAMPPRocky/tokei

Computer Graphics:
  - cnr-isti-vclab/meshlab
  - Slicer/Slicer

Desktop:
  - libpinyin/ibus-libpinyin
  - microsoft/vscode
  - obsproject/obs-studio
  - ventoy/Ventoy
  - videolan/vlc

Gaming:
  - babalae/better-genshin-impact
  - lmintlcx/pvztoolkit
  - Scighost/Starward
  - TeamFlos/phira

GitHub Actions:
  - actions/checkout
  - actions/download-artifact
  - actions/setup-node
  - actions/setup-python
  - actions/upload-artifact
  - google-github-actions/release-please-action
  - JamesIves/github-pages-deploy-action
  - pnpm/action-setup
  - xu-cheng/latex-action

GNOME:
  - corecoding/Vitals
  - micheleg/dash-to-dock
  - paperwm/PaperWM
  - ubuntu/gnome-shell-extension-appindicator

Learn:
  - 996icu/996.ICU
  - abbrcode/abbreviations-in-code
  - banach-space/llvm-tutor
  - EbookFoundation/free-programming-books
  - Hansimov/csapp
  - microsoft/ML-For-Beginners
  - practical-tutorials/project-based-learning
  - shimohq/chinese-programmer-wrong-pronunciation
  - sysprog21/lkmpg
  - The-Run-Philosophy-Organization/run
  - xinychen/latex-cookbook

Resume:
  - AmruthPillai/Reactive-Resume
  - BartoszJarocki/cv
  - said7388/developer-portfolio

Self-Hosted:
  - alist-org/alist
  - binary-husky/gpt_academic
  - ChatGPTNextWeb/ChatGPT-Next-Web
  - dani-garcia/vaultwarden
  - facebook/docusaurus
  - immich-app/immich
  - jellyfin/jellyfin
  - movie-web/movie-web
  - shuding/nextra
  - squidfunk/mkdocs-material
  - Stirling-Tools/Stirling-PDF
  - vuepress-theme-hope/vuepress-theme-hope

THU:
  - Harry-Chen/Learn-Helper
  - libthu/reserves-lib-tsinghua-downloader
  - PKUanonym/REKCARC-TSC-UHT
  - stellarkey/912_project
  - thu-cs-lab/HPC-Lab-Docs
  - THU-feiyue/docs
  - thuservices/thuservices
  - Trinkle23897/learn2018-autodown
  - z4yx/GoAuthing

Tools:
  - anuraghazra/github-readme-stats
  - lmc999/RegionRestrictionCheck
  - lowlighter/metrics
  - nkeonkeo/MediaUnlockTest

Windows:
  - massgravel/Microsoft-Activation-Scripts
  - microsoft/PowerToys
  - YerongAI/Office-Tool

Zotero:
  - MuiseDestiny/zotero-reference
  - retorquere/zotero-open-pdf
  - tefkah/zotero-night
  - windingwind/zotero-pdf-translate
  - zotero/zotero
