C/C++:
  - https://cdecl.org
  - https://en.cppreference.com
  - https://llvm.org/docs/LangRef.html
  - https://llvm.org/doxygen/classes.html
  - https://vcpkg.io/en/
  - doxygen/doxygen
  - google/sanitizers
  - microsoft/vcpkg
  - rizsotto/Bear
  - TheLartians/ModernCppStarter
  - ttroy50/cmake-examples

Go:
  - https://pkg.go.dev
  - dsnet/try
  - emirpasic/gods
  - gosimple/slug
  - mholt/archiver
  - mvdan/sh
  - otiai10/copy
  - pterm/pterm
  - sirupsen/logrus
  - spf13/cobra
  - stretchr/testify

Javascript:
  - ant-design/ant-design
  - facebook/react
  - Harry-Chen/thu-learn-lib
  - pnpm/pnpm
  - shadcn-ui/ui
  - vercel/next.js
  - vercel/vercel
  - vuejs/vue

LaTeX:
  - plk/biber
  - posquit0/Awesome-CV
  - tectonic-typesetting/tectonic
  - typst/typst

Python:
  - https://docs.python.org
  - https://pypi.org
  - agronholm/typeguard
  - astral-sh/ruff
  - benfred/py-spy
  - conda/conda
  - conda/conda-lock
  - Delgan/loguru
  - encode/httpx
  - jd/tenacity
  - mamba-org/mamba
  - matplotlib/matplotlib
  - Nuitka/Nuitka
  - numpy/numpy
  - openai/openai-python
  - openai/tiktoken
  - pandas-dev/pandas
  - Patarimi/typer-cli
  - psf/requests
  - pydantic/pydantic
  - pyinstaller/pyinstaller
  - pypa/pipx
  - pytest-dev/pytest
  - python-poetry/poetry
  - python/typeshed
  - Textualize/rich
  - tiangolo/typer
  - tmbo/questionary
  - yaml/pyyaml

Rust:
  - https://crates.io
  - https://docs.rs
  - https://lib.rs
  - https://rust-lang.org
  - https://rustwiki.org
  - ardaku/whoami
  - baoyachi/shadow-rs
  - chronotope/chrono
  - clap-rs/clap
  - clap-rs/clap-verbosity-flag
  - ConnorGray/clap-markdown
  - console-rs/console
  - console-rs/indicatif
  - dirs-dev/directories-rs
  - dtolnay/anyhow
  - jcaesar/structstruck
  - Peternator7/strum
  - rust-lang/futures-rs
  - seanmonstar/reqwest
  - serde-rs/json
  - serde-rs/serde
  - tokio-rs/tokio
  - tokio-rs/tracing
  - zhiburt/tabled

Shell:
  - charmbracelet/gum
  - charmbracelet/vhs
  - fish-shell/fish-shell
  - jorgebucaran/fisher
  - koalaman/shellcheck
  - mvdan/sh
