ACG:
  - https://bgm.tv
  - https://mikanani.me
  - https://www.agedm.org

Forums:
  - https://stackoverflow.com

Linux:
  - https://man.archlinux.org
  - https://repology.org
  - https://wiki.archlinux.org

Network:
  - https://duyaoss.com
  - https://ip.sb
  - https://ip.skk.moe
  - https://ipjiance.com
  - https://ipleak.net
  - https://speed.cloudflare.com
  - https://www.jsdelivr.com

Resources:
  - https://alternativeto.net
  - https://annas-archive.org
  - https://archive.org
  - https://byr.pt
  - https://getintopc.com
  - https://libraries.io
  - https://nav.yibook.org
  - https://oi-wiki.org
  - https://scholar.google.com
  - https://steamunlocked.net
  - https://thepiratebay.org
  - https://www.similarweb.com
  - https://ylibrary.org

Services:
  - https://app.anonaddy.com
  - https://faviconkit.com
  - https://github.com
  - https://gpt.fomepay.com
  - https://mail.proton.me
  - https://openai.com
  - https://openrouter.ai
  - https://poe.com
  - https://vault.bitwarden.com
  - https://vercel.com
  - https://web.telegram.org
  - https://www.cloudflare.com
  - https://www.namecheap.com
  - https://www.paypal.com
  - https://www.zotero.org

Tools:
  - https://chatkit.app
  - https://devhints.io
  - https://draw.io
  - https://it-tools.tech
  - https://mermaid.live
  - https://regex101.com
  - https://shenyandayi.com
  - https://slugify.online
  - https://titlecase.com
  - https://uicolors.app
  - https://www.allacronyms.com

Windows:
  - https://winstall.app
