name: Data

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  data:
    name: Data
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: data-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v2
      - name: Install Python Dependencies
        run: rye sync --no-lock
        working-directory: python
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Web Dependencies
        run: bun install --frozen-lockfile
        working-directory: web
      - name: Fetch Data
        run: make data
        env:
          GH_TOKEN: ${{ github.token }}
      - if: github.ref == 'refs/heads/main'
        name: Upload Data
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/data
          branch: data
          single-commit: true
