name: Documentation

on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docs:
    name: Documentation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Install Dependencies
        run: poetry install
      - if: github.ref != 'refs/heads/main'
        name: Build Documentation
        run: poetry run make build --jobs
        env:
          GH_TOKEN: ${{ github.token }}
      - if: github.ref == 'refs/heads/main'
        name: Deploy to GitHub Pages
        run: poetry run make gh-deploy --jobs
        env:
          GH_TOKEN: ${{ github.token }}
