name: Docs

on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  data:
    name: Data
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/data.yaml

  build:
    name: Build
    permissions:
      contents: write
    needs:
      - data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install --verbose
        working-directory: docs
      - name: Download Data
        uses: actions/checkout@v4
        with:
          ref: data
          path: docs/data
      - name: Build
        run: bun run build
        working-directory: docs
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/build

  deploy:
    name: Deploy
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          single-commit: true
