name: Docs

on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          package_json_file: docs/package.json
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
        working-directory: docs
      - name: Download Data
        uses: actions/checkout@v4
        with:
          ref: data
          path: docs/data
      - name: Build
        run: pnpm run build
        working-directory: docs
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/build

  deploy:
    name: Deploy
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          single-commit: true
